const makeCandleBtn = document.getElementById('make-candle-btn');
const sellCandlesBtn = document.getElementById('sell-candles-btn');

const candleCountElement = document.getElementById('candle-count');

const waxElement = document.getElementById('wax-count')
const moneyElement = document.getElementById('money-count')
const unsoldCandlesElement = document.getElementById('unsold-candles-count')

const autoClickerElement = document.getElementById('auto-clicker')


const constants = {
    AUTO_CLICKER_PRICE_PER_CLICK: 0.1,
    BASE_CANDLES: 10000,
    BASE_WAX: 1000,
    BASE_MONEY: 1000000,
    BASE_POSHNESS: -10000,
    WAX_PER_CANDLE: 1,
    waxPrice: {
        bee: 10,
        paraffin: 5,
        ear: 2.3
    },
    UPGRADE_CPU_PRICE: 1000,
    UPGRADE_MARKET_PRICE: 5000,
}


// const constants = {
//     AUTO_CLICKER_PRICE_PER_CLICK: 0.1,
//     BASE_CANDLES: 0,
//     BASE_WAX: 1000,
//     BASE_MONEY: 0,
//     BASE_POSHNESS: 0,
//     WAX_PER_CANDLE: 1,
//     waxPrice: {
//         bee: 10,
//         paraffin: 5,
//         ear: 2.3
//     },
//     UPGRADE_CPU_PRICE: 1000,
//     UPGRADE_MARKET_PRICE: 5000,
// }

const game = {
    candles: constants.BASE_CANDLES,
    resources: {
        unsoldCandles: constants.BASE_CANDLES,
        wax: constants.BASE_WAX,
        money: constants.BASE_MONEY,
        poshness: constants.BASE_POSHNESS
    },
    features: {
        hasAutoClicker: false,
        hasWaxCollector: false,
        hasMarketManipulation: false,
        hasDirtyMarketManipulation: false,
        hasCpu: false,
    },
    mainLoop:
        window.setInterval(function () {
            game.updateDisplay()
            game.eventCheck()
        }, 10),

    updateDisplay: function () {
        candleCountElement.innerText = formatWithCommas(game.candles)
        waxElement.innerText = formatWithCommas(game.resources.wax)
        moneyElement.innerText = formatWithCommas(game.resources.money, 2)
        unsoldCandlesElement.innerText = formatWithCommas(game.resources.unsoldCandles)
        document.getElementById("poshness-count").innerText = formatWithCommas(game.resources.poshness)
        cpu.updateUi()
        marketManipulator.updateUi()
    },
    eventCheck: function () {
        if (!game.features.hasAutoClicker && game.candles === 100) {
            writeToChat("Oof ouchie your fingers, why don't you buy something to help you with that?")
            game.features.hasAutoClicker = true
            autoClickerElement.style.display = "block"
            document.getElementById("auto-seller").style.display = "block"
            document.getElementById("cpu").style.display = "block"
        }
        if (game.resources.wax <= 0 && !game.features.hasWaxCollector) {
            writeToChat("You're out of wax, you're a 💩 - message autogenerated by Github Copilot")
            game.features.hasWaxCollector = true
            document.getElementById("poshness").style.display = "block"
            document.getElementById('wax-collector').style.display = "block"
        }

        if (game.resources.wax <= 0 && wax.autoBuyer) {
            wax.buy()
        }

        if (game.candles >= 10000 && game.resources.poshness >= 10000 && !game.features.hasMarketManipulation) {
            writeToChat("What a posh gentleman\nYou unlocked Posh Market Manipulation")
            game.features.hasMarketManipulation = true
            document.getElementById("posh-market-manipulation").style.display = "block"
        }

        if (game.candles >= 10000 && game.resources.poshness <= -10000 && !game.features.hasDirtyMarketManipulation) {
            writeToChat("You are truly disgusting\nYou unlocked Dirty Market Manipulation")
            game.features.hasDirtyMarketManipulation = true
            document.getElementById("dirty-market-manipulation").style.display = "block"
        }
    },
    candleCreated: function (amount) {
        if (game.resources.wax > 0) {
            game.candles += amount
            game.resources.wax -= amount * constants.WAX_PER_CANDLE
            game.resources.unsoldCandles += amount
            return true
        }
        return false
    },
    sellCandle: function (amount, value) {
        if (amount <= game.resources.unsoldCandles) {
            game.resources.money += amount * value
            game.resources.unsoldCandles -= amount
        }
    },
    purchase: function (amount) {
        if (amount <= game.resources.money) {
            game.resources.money -= amount
            return true
        }
        return false
    }
}



makeCandleBtn.addEventListener("click", function (e) {
    game.candleCreated(1)
})

sellCandlesBtn.addEventListener("click", function (e) {
    game.sellCandle(game.resources.unsoldCandles, market.currentPrice)
})


// document is loaded
window.addEventListener("load", async function (e) {
    await writeToChat("Hello there...")
    await writeToChat("So you're here expecting a challenge?")
    await writeToChat("Just chill and make some candles!")
})